### ISSUE TITLE
Adjust Application Plumbing to K8up

### ISSUE THREAD

**Issue by tobru** [projectsyn/lieutenant-operator#135]
## Context

In [K8up](https://github.com/vshn/k8up) we put a lot of effort in the plumbing of the operator. Adjust this repository to adhere to the plumbing of K8up. This includes:

* [x] GitHub issue templates
* [x] GitHub actions
* [x] Release workflow
* [x] automated Changelog generation ->  Done in #170 
* [x] Plumbing for testing

**Comment by ccremer** [comment]
Done with #175
