### ISSUE TITLE
Implement GitRepo DisplayName

### ISSUE THREAD

**Issue by srueg** [projectsyn/lieutenant-operator#34]
Implement `DisplayName` field for GitRepos. This should be set on the created Git repository as description (i.e. GitLab: "Project description", GitHub: "Description").
The operator should default this field with the DisplayName of the tenant or cluster if possible.

## Task Deliverables
- [ ] New CRD field "DisplayName"
- [ ] Sync the display name of the tenant or cluster respectively

**Comment by srueg** [comment]
Starting points in the code:
* Create function: https://github.com/projectsyn/lieutenant-operator/blob/573ce40470216b5f180a14d0a6af04c5352c4751/pkg/git/gitlab/gitlab.go#L63
* Update function: https://github.com/projectsyn/lieutenant-operator/blob/573ce40470216b5f180a14d0a6af04c5352c4751/pkg/git/gitlab/gitlab.go#L63
* CRD type: https://github.com/projectsyn/lieutenant-operator/blob/573ce40470216b5f180a14d0a6af04c5352c4751/pkg/apis/syn/v1alpha1/gitrepo_types.go#L50

**Comment by ZuGao** [comment]
I'm currently working on implementing this feature.
* The necessary go structures have been updated with field `DisplayName`
* The `Create()` function has been updated accordingly
* The `Update()`function is still being worked on.

After we finish with development we will add unit tests.

**Comment by ZuGao** [comment]
Created a [PullRequest](https://github.com/projectsyn/lieutenant-operator/pull/49) for this issue

**Comment by srueg** [comment]
Implemented with https://github.com/projectsyn/lieutenant-operator/pull/49
