### ISSUE TITLE
Implement Tenant GitRepo Bootstrapping

### ISSUE THREAD

**Issue by srueg** [projectsyn/lieutenant-operator#36]
Automate creation of cluster config file in tenant configuration repository.
For each new cluster, an empty YAML file needs to be created in the tenant's config repo. The file **must** be called `$CLUSTER_ID.yml` (note the `.yml` **without** `a`)

## Task Deliverables

- [ ] Operator automatically creates `$CLUSTER_ID.yml` files in the tenant repo

**Comment by Kidswiss** [comment]
Started to implement this in branch `git/bootstrapping`.

I'm implementing some generalised bootstrap handling so that we can commit an arbitrary amount of files into the repository.

**Comment by Kidswiss** [comment]
Commiting files into a repository is now implemented.

The CRD for the GitRepository was extended in a way that it can hold a map of file/content pairs. Each of these entries will be committed to the repository upon the next reconcile loop.

I also found and fixed two annoying bugs that cost me way to much time to find.

Still to do:

- [ ] unit test where ever possible

**Comment by Kidswiss** [comment]
There are now unit tests for the new functionality. While implementing them I already found a minor bug that I fixed.

@srueg would you have a look at #42 ?

THX

**Comment by Kidswiss** [comment]
Changes merged, closing here.
