### ISSUE TITLE
Write Documentation

### ISSUE THREAD

**Issue by srueg** [projectsyn/lieutenant-operator#37]
Write some basic documentation about this tool. Reuse as much as possible from the SDD: https://github.com/projectsyn/documentation/blob/master/docs/modules/SDDs/pages/0007-lieutenant-management-api.adoc
If possible, generate documentation for the OpenAPI CRDs (e.g. using [gen-crd-api-reference-docs](https://github.com/ahmetb/gen-crd-api-reference-docs)) and include it in the Antora docs.

## Task Deliverables

- [ ] Basic documentation about lieutenant-operator

**Comment by Kidswiss** [comment]
I added a bit of a hacky script to`generate.go` which uses your linked generator to generate a html file for our CRDs. That file in turn is included in the asciidoc documentation.

I also transferred everything from the SDD to this repo. The CRD topics are now a bit redundant. Should I remove the SDD CRD definitions in favour of the concrete implementations? @srueg

**Comment by srueg** [comment]
Nice! Yes good point. I think only leaving the generated part is ok.

**Comment by Kidswiss** [comment]
Implemented your feedback and removed the old CRD documentation.

**Comment by Kidswiss** [comment]
Unfortunately the html include does not work currently: https://docs.syn.tools/lieutenant-operator/crds-html.html

Will investigate

**Comment by srueg** [comment]
@akosma can you please add the Makefile setup for Antora to this repo (and also include it in the GitHub action)?

**Comment by Kidswiss** [comment]
After quite some investigation I found two things:
* the include has to be done in a special manner for Antora to pick it up
* I needed to adjust the HTML templates used to generate the CRD docs so it will get the right styling

Lokal renders look good now:
![image](https://user-images.githubusercontent.com/7460550/79337167-52ecf580-7f25-11ea-825c-08bea10fd4bc.png)

@srueg Can you have a look and merge if everything looks good to you? THX

**Comment by srueg** [comment]
Looking good 👍 https://syn.tools/lieutenant-operator/crds-html.html

**Comment by Kidswiss** [comment]
Nice!

The docs now look good, closing here.
