### ISSUE TITLE
Rework Documentation of Lieutenant Operator

### ISSUE THREAD

**Issue by tobru** [projectsyn/lieutenant-operator#77]
Currently the documentation of Lieutenant Operator is very scarce and should be updated to make using and understanding the Lieutenant Operator a breeze.

The documentation should:

* describe the concept of Lieutenant Operator: What does it do? How does it work?
* show the configuration options

Also the start page of https://syn.tools/lieutenant-operator/index.html should give a short intro to Lieutenant Operator, so that it gives an idea what it's all about.

Adhere to https://documentation.divio.com/ for putting the pages and content into the right context.

**Comment by Kidswiss** [comment]
Reweorded the documentation according to https://documentation.divio.com/.

As the operator is mainly meant to be used with the API the tutorial section doesn't really provide much except the installation. Maybe some suggestions what could be added there?

**Comment by Kidswiss** [comment]
Chnages were merged
