### ISSUE TITLE
Upgrade to Operator SDK 1.3

### ISSUE THREAD

**Issue by tobru** [projectsyn/lieutenant-operator#95]
## Context

The Operator SDK lately [reached 1.0](https://www.openshift.com/blog/operator-sdk-reaches-v1.0) and later [1.1](https://github.com/operator-framework/operator-sdk/releases/tag/v1.1.0) up till [1.3](https://github.com/operator-framework/operator-sdk/releases/tag/v1.3.0). The Lieutenant Operator currently uses v0.17.1, so it's time to upgrade to stay on a supported path.

See https://sdk.operatorframework.io/docs/upgrading-sdk-version/ for help to upgrade.

## Alternatives

There is none, upgrading is an important pillar keeping software up-to-date.

**Comment by cimnine** [comment]
This was pre-released in https://github.com/projectsyn/lieutenant-operator/releases/tag/v1.0.0-rc.1

**Comment by bastjan** [comment]
With a long string of dependency updates and simplification operator-sdk is removed completely from this project https://github.com/projectsyn/lieutenant-operator/pull/265.
